Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,5 +1,6 @@
 name: Prisma Cloud Shift Left demo
-on: [ push,pull_request ]
+on: [ pull_request ]
+
 
 jobs:
   prisma_cloud_job:
@@ -8,69 +9,72 @@ jobs:
     env:
           TL_USER: ${{ secrets.TL_USER }}
           TL_PASS: ${{ secrets.TL_PASS }}
-          TL_CONSOLE: ${{ secrets.TL_CONSOLE }}
+          TL_CONSOLE: ${{ secrets.TL_CONSOLE }} 
           BYPASS_REPOSCAN: 0
           BYPASS_OSS_LICENSE: 0
           BYPASS_IMAGESCAN: 0
-          BYPASS_WF: 0
-          BYPASS_SANDBOX: 0
-          PROJECT_ID: ${{ secrets.GKE_PROJECT }}
-          GKE_CLUSTER:  itresoldi-gke-pcc
+          BYPASS_WF: 1
     steps:
     
       - name: Checkout
         uses: actions/checkout@v2
-    
+        
       - name: twistcli download
-        run: bash ./files/download_twistcli.sh
-    
+        run: curl -s -k -u $TL_USER:$TL_PASS "https://$TL_CONSOLE/api/v1/util/twistcli" -v -o twistcli;chmod +x twistcli
+
       - name: Repo Vulnerability scan 
         run: bash ./files/repoScan.sh
 
       - name: OSS License Check 
         run: bash ./files/licenseCheck.sh
 
-      - name: Apply security policies (Policy-as-Code) for evilpetclinic Application
+      - name: Apply security policies (Policy-as-Code) for evilpetclinic
         run: bash ./files/addPolicies.sh
       
       - name: Scan Image for vulnerabilities
         run: bash ./files/scanImage.sh
+   
+
+    #  - name: IaC scan of files in the repository
+    #    uses: prisma-cloud-shiftleft/iac-scan-action@v1
+    #    id: iac-scan
+    #    with:
+    #      prisma_api_url: 'https://api.prismacloud.io'
+    #      access_key: ${{ secrets.PRISMA_CLOUD_ACCESS_KEY }}
+    #      secret_key: ${{ secrets.PRISMA_CLOUD_SECRET_KEY }}
+    #      asset_name: 'shiftleft-github-actions'
+    #      template_type: 'K8S'
+    #      failure_criteria: High:3,Medium:3,Low:10,Operator:or
+    #      scan_path: ./files    
+      
+    #  - name: Upload scan result artifact
+    #    uses: actions/upload-artifact@v2
+    #    if: success() || failure()
+    #    with:
+    #      name: iac_scan_result
+    #      path: ${{ steps.iac-scan.outputs.iac_scan_result_path }}
       
       - name: Scan Image for Malware using Wildfire
         run: bash ./files/malwareCheck.sh
         
-      - name: Sandbox Runtime Scanning of Image
-        run: bash ./files/sandboxscan.sh
         
-      - name: Run Bridgecrew/Checkov IaC scanning action
-        id: checkov
+      - name: Run Bridgecrew action
+        id: Bridgecrew
         uses: bridgecrewio/checkov-action@master
         with:
-          api-key: ${{ secrets.BRIDGECREW_API_KEY }}
           directory: ./files
           soft_fail: true # optional: do not return an error code if there are failed checks
+          api-key: ${{ secrets.BC_API_KEY }}
           framework: kubernetes # optional: run only on a specific infrastructure {cloudformation,terraform,kubernetes,all}
           quiet: true
           output_format: github_failed_only # optional: the output format, one of: cli, json, junitxml, github_failed_only
           log_level: WARNING # optional: set log level. Default WARNING
           
-      # Setup gcloud CLI
-      - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
-        with:
-          service_account_key: ${{ secrets.GKE_SA_KEY }}
-          project_id: ${{ secrets.GKE_PROJECT }}
-          
-      # Get the GKE credentials so we can deploy to the cluster
-      - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
-        with:
-          cluster_name: ${{ env.GKE_CLUSTER }}
-          credentials: ${{ secrets.GKE_SA_KEY }}
-          
-      - name: Deploy evilpetclinic Application
-        run: bash ./deploy.sh
+      - name: Deploy evilpetclinic app
+        run: bash files/exec.sh deploy.sh
         
-      - name: Execute Runtime attacks
-        run: bash ./runtime_attacks.sh
+      - name: Runtime attacks
+        run: bash files/exec.sh runtime_attacks.sh
           
-      - name: Execute WAAS attacks
-        run: bash ./waas_attacks.sh
+      - name: WAAS attacks
+        run: bash files/exec.sh waas_attacks.sh
